import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import { Navbar } from "../components/Navbar/navbar";
import Footer from "@/components/footer/Footer";
import { Metadata } from "next";
import ScrollToTop from "@/components/SrollToTop";
import { ThemeProvider } from "next-themes";
import { Suspense } from "react";
import { LoadingManager } from "three";
import { VscLoading } from "react-icons/vsc";
import { AiOutlineLoading } from "react-icons/ai";
import Starbackground from "@/components/Starbackground";

const geistSans = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

//  eslint-disable-next-line @typescript-eslint/no-unused-vars
export const metadata: Metadata = {
  title: "Azharul Islam | Home",
  description: "Generated by create next app",
  icons: "https://azharul-islam-b901c.web.app/assets/logo-b35e1245.png",
};

// eslint-disable-next-line @typescript-eslint/no-unused-vars

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
      />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense
          fallback={<AiOutlineLoading className="animate-spin text-3xl " />}
        >
          <ThemeProvider attribute="class" defaultTheme="dark">
            <Providers>
              <header className="  ">
                <Navbar />
              </header>
              <Starbackground>{children}</Starbackground>
              <footer className="container mx-auto ">
                <Footer />
              </footer>
              <ScrollToTop />
            </Providers>
          </ThemeProvider>
        </Suspense>
      </body>
    </html>
  );
}
