import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import { Navbar } from "../components/Navbar/navbar";
import Footer from "@/components/footer/Footer";
import { Metadata } from "next";

const geistSans = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

//  eslint-disable-next-line @typescript-eslint/no-unused-vars
export const metadata: Metadata = {
  title: "Portfolio | Home",
  description: "Generated by create next app",
  icons: "https://azharul-islam-b901c.web.app/assets/logo-b35e1245.png"
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers >
          <header className="w-full! mx-auto md:px-0 px-3 bg-gray-500">
            <Navbar />
          </header>
          {children}
          <footer className="container mx-auto md:px-0 px-3">
            <Footer />
          </footer>

        </Providers>
      </body>
    </html>
  );
}
